version: '3.7'

services:
  backend:
    build:
      context: ./dutluk_backend
    container_name: dutluk-backend
    image: hdenizdogan/dutluk-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./dutluk_frontend/.env
    depends_on:
      - db
    volumes:
      - backend-data:/path/to/backend/data
    restart: always

  frontend:
    build:
      context: ./dutluk_frontend
    container_name: dutluk-frontend
    image: hdenizdogan/dutluk-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./dutluk_frontend/.env
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: dutluk-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./dutluk_frontend/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      
   
  recengine:
    build:
      context: ./dutluk_rs
    container_name: rec-engine
    image: hdenizdogan/rec-engine:latest
    env_file:
      - ./dutluk_frontend/.env
    ports:
      - "8000:8000"
    restart: always

volumes:
  backend-data:
  db-data:


#sudo su -
#apt-get update
#apt-get install docker-compose
#apt-get install git
#git clone https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2
#cd BOUN-SWE-574-Fall-23-G2/
#cd dutluk/
#cd dutluk_frontend/
#nano .env (paste the necessary env variables here)
#cd ..
#docker compose up --build -d 
