version: '3.7'
services:
  backend:
    build:
      context: ./dutluk_backend
    container_name: dutluk-backend
    ports:
      - "8080:8080"
    env_file:
      - ./dutluk_frontend/.env
    depends_on:
      - db

  frontend:
    build: 
        context: ./dutluk_frontend
    container_name: dutluk-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./dutluk_frontend/.env
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./dutluk_frontend/.env


#docker compose up --build -d