// Mocks generated by Mockito 5.4.3 from annotations
// in swe/test/story/story_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i17;

import 'package:busenet/busenet.dart' as _i9;
import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/src/widgets/framework.dart' as _i5;
import 'package:flutter/src/widgets/notification_listener.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:swe/_domain/auth/model/follow_user_model.dart' as _i16;
import 'package:swe/_domain/auth/model/profile_update_model.dart' as _i15;
import 'package:swe/_domain/auth/model/user.dart' as _i3;
import 'package:swe/_domain/profile/i_profile_repository.dart' as _i14;
import 'package:swe/_domain/story/i_story_repository.dart' as _i7;
import 'package:swe/_domain/story/model/addStory_model.dart' as _i10;
import 'package:swe/_domain/story/model/comment_model.dart' as _i11;
import 'package:swe/_domain/story/model/getNearbyStories_model.dart' as _i4;
import 'package:swe/_domain/story/model/postComment_model.dart' as _i12;
import 'package:swe/_domain/story/model/story_filter.dart' as _i13;
import 'package:swe/_domain/story/model/story_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$StoryModelCopyWith_0<$Res> extends _i1.SmartFake
    implements _i2.$StoryModelCopyWith<$Res> {
  _Fake$StoryModelCopyWith_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoryModel_1 extends _i1.SmartFake implements _i2.StoryModel {
  _FakeStoryModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$UserCopyWith_2<$Res> extends _i1.SmartFake
    implements _i3.$UserCopyWith<$Res> {
  _Fake$UserCopyWith_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_3 extends _i1.SmartFake implements _i3.User {
  _FakeUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$GetNearbyStoriesModelCopyWith_4<$Res> extends _i1.SmartFake
    implements _i4.$GetNearbyStoriesModelCopyWith<$Res> {
  _Fake$GetNearbyStoriesModelCopyWith_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetNearbyStoriesModel_5 extends _i1.SmartFake
    implements _i4.GetNearbyStoriesModel {
  _FakeGetNearbyStoriesModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_6 extends _i1.SmartFake implements _i5.Widget {
  _FakeWidget_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_7 extends _i1.SmartFake
    implements _i5.InheritedWidget {
  _FakeInheritedWidget_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_8 extends _i1.SmartFake
    implements _i6.DiagnosticsNode {
  _FakeDiagnosticsNode_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i6.TextTreeConfiguration? parentConfiguration,
    _i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [IStoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIStoryRepository extends _i1.Mock implements _i7.IStoryRepository {
  MockIStoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getAllStory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllStory,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getActivityFeed() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityFeed,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getFallowedStories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFallowedStories,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getNearbyStories(
          _i4.GetNearbyStoriesModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyStories,
          [model],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getRecommendedStories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedStories,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> myStories() =>
      (super.noSuchMethod(
        Invocation.method(
          #myStories,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, bool?)> deleteStory(int? storyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteStory,
          [storyId],
        ),
        returnValue: _i8.Future<(_i9.Failure?, bool?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, bool?)>);
  @override
  _i8.Future<(_i9.Failure?, _i2.StoryModel?)> getStoryDetail(int? storyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoryDetail,
          [storyId],
        ),
        returnValue:
            _i8.Future<(_i9.Failure?, _i2.StoryModel?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i2.StoryModel?)>);
  @override
  _i8.Future<(_i9.Failure?, _i2.StoryModel?)> addStoryModel(
          _i10.AddStoryModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStoryModel,
          [model],
        ),
        returnValue:
            _i8.Future<(_i9.Failure?, _i2.StoryModel?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i2.StoryModel?)>);
  @override
  _i8.Future<(_i9.Failure?, _i2.StoryModel?)> addFavorite(
          {required int? itemId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [],
          {#itemId: itemId},
        ),
        returnValue:
            _i8.Future<(_i9.Failure?, _i2.StoryModel?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i2.StoryModel?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getLikedStories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedStories,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getRecentStories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentStories,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, _i11.CommentModel?)> postComment(
          _i12.PostCommentModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #postComment,
          [model],
        ),
        returnValue:
            _i8.Future<(_i9.Failure?, _i11.CommentModel?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i11.CommentModel?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getSearchStories(
    _i13.StoryFilter? storyFilter,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchStories,
          [
            storyFilter,
            searchTerm,
          ],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getTimelineSearchStories(
    _i13.StoryFilter? storyFilter,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimelineSearchStories,
          [
            storyFilter,
            searchTerm,
          ],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
  @override
  _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)> getTagSearchStories(
          String? label) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagSearchStories,
          [label],
        ),
        returnValue: _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>.value(
            (null, null)),
      ) as _i8.Future<(_i9.Failure?, List<_i2.StoryModel>?)>);
}

/// A class which mocks [IProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRepository extends _i1.Mock
    implements _i14.IProfileRepository {
  MockIProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<(_i9.Failure?, _i3.User?)> getUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [],
        ),
        returnValue: _i8.Future<(_i9.Failure?, _i3.User?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i3.User?)>);
  @override
  _i8.Future<(_i9.Failure?, _i3.User?)> updateUserInfo(
          _i15.ProfileUpdateModel? bio) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [bio],
        ),
        returnValue: _i8.Future<(_i9.Failure?, _i3.User?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i3.User?)>);
  @override
  _i8.Future<(_i9.Failure?, _i3.User?)> followUser(
          _i16.FollowUserModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [model],
        ),
        returnValue: _i8.Future<(_i9.Failure?, _i3.User?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i3.User?)>);
  @override
  _i8.Future<(_i9.Failure?, _i3.User?)> otherProfile(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #otherProfile,
          [id],
        ),
        returnValue: _i8.Future<(_i9.Failure?, _i3.User?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i3.User?)>);
  @override
  _i8.Future<(_i9.Failure?, _i3.User?)> profileImageUpdate(_i17.File? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #profileImageUpdate,
          [file],
        ),
        returnValue: _i8.Future<(_i9.Failure?, _i3.User?)>.value((null, null)),
      ) as _i8.Future<(_i9.Failure?, _i3.User?)>);
}

/// A class which mocks [StoryModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoryModel extends _i1.Mock implements _i2.StoryModel {
  MockStoryModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
      ) as int);
  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
      ) as String);
  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);
  @override
  _i2.$StoryModelCopyWith<_i2.StoryModel> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$StoryModelCopyWith_0<_i2.StoryModel>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$StoryModelCopyWith<_i2.StoryModel>);
  @override
  _i2.StoryModel fromJson(dynamic data) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [data],
        ),
        returnValue: _FakeStoryModel_1(
          this,
          Invocation.method(
            #fromJson,
            [data],
          ),
        ),
      ) as _i2.StoryModel);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.$UserCopyWith<_i3.User> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$UserCopyWith_2<_i3.User>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$UserCopyWith<_i3.User>);
  @override
  _i3.User fromJson(dynamic data) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [data],
        ),
        returnValue: _FakeUser_3(
          this,
          Invocation.method(
            #fromJson,
            [data],
          ),
        ),
      ) as _i3.User);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [GetNearbyStoriesModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNearbyStoriesModel extends _i1.Mock
    implements _i4.GetNearbyStoriesModel {
  MockGetNearbyStoriesModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.$GetNearbyStoriesModelCopyWith<_i4.GetNearbyStoriesModel> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue:
            _Fake$GetNearbyStoriesModelCopyWith_4<_i4.GetNearbyStoriesModel>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i4.$GetNearbyStoriesModelCopyWith<_i4.GetNearbyStoriesModel>);
  @override
  _i4.GetNearbyStoriesModel fromJson(dynamic data) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [data],
        ),
        returnValue: _FakeGetNearbyStoriesModel_5(
          this,
          Invocation.method(
            #fromJson,
            [data],
          ),
        ),
      ) as _i4.GetNearbyStoriesModel);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i5.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_6(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i5.Widget);
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);
  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);
  @override
  _i5.InheritedWidget dependOnInheritedElement(
    _i5.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_7(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i5.InheritedWidget);
  @override
  void visitAncestorElements(_i5.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void visitChildElements(_i5.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispatchNotification(_i19.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.DiagnosticsNode describeElement(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_8(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i6.DiagnosticsNode);
  @override
  _i6.DiagnosticsNode describeWidget(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_8(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i6.DiagnosticsNode);
  @override
  List<_i6.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i6.DiagnosticsNode>[],
      ) as List<_i6.DiagnosticsNode>);
  @override
  _i6.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_8(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i6.DiagnosticsNode);
}
