include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - "lib/injection.config.dart"
    - test
    - assets/translations
    
linter:
  rules:
    always_use_package_imports: false
    public_member_api_docs: false
    cascade_invocations: false
    sort_constructors_first: false
    use_setters_to_change_properties: false
    use_build_context_synchronously: false
    empty_catches: false
    avoid_bool_literals_in_conditional_expressions: false
    eol_at_end_of_file: false
    avoid_positional_boolean_parameters: false
    lines_longer_than_80_chars: false
    avoid_dynamic_calls: false