name: swe
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  busenet: ^0.7.0+4
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.1
  envied: ^0.3.0+3
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.3.4
  firebase_dynamic_links: ^5.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_quill: ^7.4.7
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  lottie: ^2.3.1
  onesignal_flutter: ^3.5.1
  share_plus: ^7.1.0
  shared_preferences: ^2.0.18
  html: ^0.15.4
  flutter_quill_extensions: ^0.5.0
  intl: ^0.18.1
  omni_datetime_picker: ^1.0.9
  

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: null
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/i10n/
    - assets/lottie/
    - assets/images/
