# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dutluk-fe-test

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_14afa918bbbd466aba6c10063a6a99ad }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4db170804c17443a8e41144b20389a90 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_14afa918bbbd466aba6c10063a6a99ad }}/docket-fe-test:${{ github.sha }}
        file: ./dutluk/build_dockerfiles/frontend/Dockerfile
        build-args: REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL_TEST }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dutluk-fe-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d220ad91851c44aca6efa987d30dee69 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_14afa918bbbd466aba6c10063a6a99ad }}/docket-fe-test:${{ github.sha }}'
