# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dutluk-fe-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c5ec559191f2491a88af5504a08339fa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_77eb8deb08794aceb893a0ca1ab6db21 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c5ec559191f2491a88af5504a08339fa }}/dutluk-fe-prod:${{ github.sha }}
        file: ./dutluk/build_dockerfiles/frontend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dutluk-fe-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f51234fe44494b21959d0d250e8e7af7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c5ec559191f2491a88af5504a08339fa }}/dutluk-fe-prod:${{ github.sha }}'
